### ISSUE TITLE
ユニットテストで「クラス Managerのメソッド terminateは指定された型 に適用できません」のエラーが発生する

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTM-aist-Java#44]
**Describe the bug**
ユニットテストスクリプト buildTests.sh を実行するとエラーが発生する
```
    [javac] /home/openrtm/java/OpenRTM-aist-Java/jp.go.aist.rtm.RTC/tests/src/jp/go/aist/rtm/RTC/ManagerTest.java:407: エラー: クラス Managerのメソッド terminateは指定された型に適用できません。
    [javac]         m_mgr.terminate();
    [javac]              ^
    [javac]   期待値: double
    [javac]   検出値: 引数がありません
    [javac]   理由: 実引数リストと仮引数リストの長さが異なります
```

**To Reproduce**
1. buildRTC.sh を実行
2. 続けて buildTests.sh を実行

**Environment**
 - OS:  Ubuntu 16.04 64bits
 - OpenRTM-aist-Java 2.0, 1.2

**Additional context**
Travis CIで試した下記ymlにて同じエラーを確認 
```
dist: xenial
language: java

addons:
  apt:
    packages:
    - ant
    - junit

jdk:
  - openjdk8

script:
  - bash buildRTC.sh
  - bash buildTests.sh
```
